version: "3" ## especifica a versão do docker-compose file

services:

  mongo:
    image: mongo
    container_name: mongo-dev
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: teste
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - "./data/mongo:/var/lib/docker/mongo/data"
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '1.5'
        reservations:
          memory: 512M
